JD-378: New payouts processing
rbkmoney/magista pull request #302
Opened 2021-06-22 16:20 UTC by inallyoung

2021-06-24 16:47 UTC, karleowne commented on src/main/java/com/rbkmoney/magista/serde/PayoutEventDeserializer.java
> +public class PayoutEventDeserializer implements Deserializer<Event> {
у нас в библе кафки есть десериалайзер, там можно его просто наследовать в сервисе

2021-06-24 16:47 UTC, karleowne commented on src/main/resources/application.yml
> +    payout: mg-payout
топик будет payout скорее всего (так указал в мастере payout-maanger)

2021-06-24 16:47 UTC, karleowne commented on src/main/resources/db/migration/V24__new_payouts.sql
> +    fee              bigint default 0,
тут можно отформатить + не понятно почему только для fee ставим default 0 . я реализовал в манегере 
```
 amount         bigint           not null default 0,
    fee            bigint           not null default 0,
    currency_code  varchar          not null,
    sequence_id    integer          not null default 0,
    ```

2021-06-24 21:59 UTC, inallyoung commented on src/main/resources/db/migration/V24__new_payouts.sql
> +    fee              bigint default 0,
отформаттил, только, как мне кажется, не корректно у amount делать по дефолту 0. У выплаты обязательно ненулевая сумма, и в данном случае неправильно в качестве дефолта выставлять невозможную сумму.
Для fee это оправдано, допустим, у нас может быть нулевая комиссия (для вип-мерчантов, не знаю).
Что касается sequence_id, то тоже не стал бы делать дефолтом 0. Это поле участвует в проверке на дубли и если забыть его указать и там подставится 0, то это порушит логику проверки. Лучше строго контролировать его сет, оставив только проверку на not null.

2021-06-25 05:51 UTC, karleowne commented on pom.xml
> +        <version>1.2.7</version>
можно кстати бампануть pg-embedded-plugin на 1.7 , тогда у тебя локально будет без проблем собираться (если они были , как у меня)

2021-06-25 08:27 UTC, karleowne approved these changes

2021-06-25 08:47 UTC, karleowne requested changes
https://github.com/rbkmoney/payout-manager-proto/pull/8

2021-06-25 12:20 UTC, karleowne approved these changes
разобрались с протоколом

2021-07-14 05:00 UTC, dinama commented
Дайте разъяснения по протоколу https://github.com/rbkmoney/magista#payouts
Там отсылка на payout_processing.PayoutType во-первых, устаревшая. во-вторых, там не учтен новый PaymentInstitution. Мне кажется payouter это тоже касается.

2021-07-14 05:16 UTC, dinama commented
а, вижу параметр payout_type  теперь может принимать значения - russian_bank_account, international_bank_account, wallet_info, payment_institution_account. верно-ли я понимаю, что нужно подождать синхронизации этих изменений с https://github.com/rbkmoney/damsel/blob/master/proto/payout_processing.thrift#L166

2021-07-14 17:07 UTC, dinama approved these changes

2021-07-14 19:41 UTC, dinama commented
Сошлись на том, что оставляем такой перечень
bank_account (про причине обратной совместимости с api) +  domain.PayoutToolInfo

2021-07-14 19:52 UTC, dinama commented
пересошлись на том, что добавится только payment_institution_account

2021-07-15 08:21 UTC, karleowne commented on src/main/java/com/rbkmoney/magista/event/mapper/impl/PayoutCreatedMapper.java
> +        if (payoutToolInfo.isSetRussianBankAccount()) {
PayoutToolInfo который вернется из partyManagementService тут может быть null , отсюда может выскочить npe
оставляем так?

2021-07-15 14:14 UTC, inallyoung commented on src/main/java/com/rbkmoney/magista/event/mapper/impl/PayoutCreatedMapper.java
> +        if (payoutToolInfo.isSetRussianBankAccount()) {
пофиксил

2021-07-15 14:41 UTC, karleowne submitted a review, later dismissed

2021-07-28 15:32 UTC, karleowne approved these changes
если @dinama не против

2021-07-29 13:11 UTC, karleowne approved these changes
@dinama 💚

2021-07-29 13:17 UTC, merged